@startuml DiagramaClasesCitas

top to bottom direction

class Usuario
class Medico
class Administrador
class Enfermera
class Paciente
class Agenda
class AgendaMedico
class AgendaEnfermera
class Lugar
class Cita
class HistoriaClinica
class Procedimiento

'Relaciones de herencia

Usuario <|-down- Medico
Usuario <|-down- Administrador
Usuario <|-down- Enfermera
Usuario <|-down- Paciente

Agenda <|-down- AgendaMedico
Agenda <|-down- AgendaEnfermera

'Relaciones de cardinalidad

Paciente "1" *-- "*" HistoriaClinica : Tiene
Paciente "1" *-- "*" Cita : Aparta

Medico "1" *--- "1" AgendaMedico : Tiene

Enfermera "1" *-- "1" AgendaEnfermera : Tiene

Cita "1" o-- "1" Lugar : Se desarrolla en
Procedimiento "1" -up-o "*" Cita : se desarrolla en
Agenda "1" o-- "*" Cita : Contiene

'Especialidad seria un atributo del medico
'Tipo de cita seria un atributo de la cita


@enduml
